name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 23ds3000003@ds.study.iitm.ac.in
        run: echo "Hello, world!"
